### ISSUE TITLE
Pull Popup

### ISSUE THREAD

**Issue by TimUntersberger** [TimUntersberger/neogit#14]
### Actions

- [x] Pull from pushremote
- [ ] Pull from upstream
- [ ] Pull from elsewhere

**Comment by koopa1338** [comment]
@TimUntersberger this is already working isn't it? If not, what is missing (would appreciate to support here)?

**Comment by TimUntersberger** [comment]
@koopa1338 you are right! Thank you!
